### ISSUE TITLE
[BUG] Numbering of hits

### ISSUE THREAD

**Issue by Meriadocus** [emanjavacas/cleebo#15]
When after having marked hits a new query is submitted that includes the marked hits as well as some new results, the numbering is renewed only partially. 

For example
First query
("going" "to" "be" "a") | ("going" "to" "be" "the")
yields 7 hits, numbered 1-7. 
User marks all of them. 

Second query
("going" "to" "be" "a") | ("going" "to" "be" "the") | ("going" "to" "be" "judged")
yields 11 hits. 

Now the first 8 of these are numbered 1-8, but then the next 3 (which were the final results of the first query, and had been marked) are numbered 5-7 again. 

This might lead to confusion though it's only a minor issue. Not clear to me what a good solution would be though.

**Comment by emanjavacas** [comment]
Both of your queries overlap (since one defines a subset of the other). I am retaining loaded hits (+ metadata) so that in case a subsequent query (e.g. next or previous page) retrieves the same hits the metadata can be reapplied to those hits but forgot to do full rewrite in case of a new query. Anyway, 71d70cc3208a1118fd91336e2be044fa5ec4ef3b should've fixed it

**Comment by emanjavacas** [comment]
The new solution is not optimal cause it removes all stored hits (including info as to whether which were marked or not). A better solution will handle this modifying src/cljs.cosycat.backend.handlers.query/merge-results
